### ISSUE TITLE
Зависимость от support design library

### ISSUE THREAD

**Issue by tberchanov** [dmdevgo/RxPM#15]
Создал проект но не подключил к нему support design library. 
Выпадала ошибка: error: cannot access TextInputLayout class file for android.support.design.widget.TextInputLayout not found Consult the following stack trace for details.
После подключения support design library все начало работать нормально.

**Comment by Jeevuz** [comment]
Thanks for adding this. As we already discussed in the chat we will try to overcome this issue and make the support optional. By the way we plan to adopt the library to the new material components package.

**Comment by Jeevuz** [comment]
We've looked into it. There is different compilator behavior in Kotlin and in Java. So this error is only when using the library in Java project. 
@dmdevgo created an issue in the Kotlin tracker https://youtrack.jetbrains.com/issue/KT-25742. 
Because this is Java only issue and the library mainly targets the Kotlin projects, I think we can close the issue until new incoming data.
