### ISSUE TITLE
Question about unsubscribes

### ISSUE THREAD

**Issue by wpbloger** [dmdevgo/RxPM#48]
Hello.
In the examples, you have a code in which, when subscribing to Action, there is a call to the untilDestroy helper method when subscribing to Action.
There are also examples in View (Activity/Fragment) where a quick method is used that also unsubscribes from a property.
And I had a question whether I really need to unsubscribe.
Suppose I have a Presentation Model and an action, I subscribe to it, and when the Presentation Model is destroyed, does the garbage collector not clear all the Action resources since there are no references to it outside the life cycle of the Presentation Model.
The same thing about subscribing to a state in a view (activity/fragment).
Maybe my question seems stupid, but I would like to figure it out here.

**Comment by Jeevuz** [comment]
Hi! That's not really about the library, but:
GC will collect the objects later. And you don't want to wait for this because you can't guaratee when it will happen. 
And if your subscription is alive and PM is not yet collected by GC, you don't want some actions to happen accidentally (eg. some network call responded and you will do some work in PM...). 
So the right way to unsubscribe when you no longer need the subscription. 

I will close the issue, but feel free to ask.
